#ifndef CONFIG_H
#define CONFIG_H

#define CENTAUROS_TOTAL_INTR 512
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define CENTAUROS_HEAP_SIZE_BYTES 104857600 // 100MB heap
#define CENTAUROS_HEAP_BLOCK_SIZE 4096
#define CENTAUROS_HEAP_ADDRESS 0x01000000
#define CENTAUROS_HEAP_TABLE_ADDRESS 0x00007E00

#define CENTAUROS_SECTOR_SIZE 512

#define CENTAUROS_MAX_FILESYSTEMS 12
#define CENTAUROS_MAX_FILE_DESCRIPTORS 512
#define CENTAUROS_MAX_PATH 108

#define CENTAUROS_TOTAL_GDT_SEGMENTS 6

#define CENTAUROS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define CENTAUROS_USER_RPOGRAM_STACK_SIZE 1024 * 16
#define CENTAUROS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define CENTAUROS_PROGRAM_VIRTUAL_STACK_ADDRESS_END CENTAUROS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - CENTAUROS_USER_RPOGRAM_STACK_SIZE

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#define CENTAUROS_MAX_PROGRAM_ALLOCATIONS 1024
#define CENTAUROS_MAX_PROCESSES 12

#define CENTAUROS_MAX_ISR80H_COMMANDS 1024

#endif